"""Render the live OpenAPI schema to .github/wiki/API-reference.md.

Purpose    : Keep the committed API reference in lock-step with the code —
             the local drift check (definition_of_done) re-runs this and
             diffs the result against HEAD; CI does the same from E14.
Inputs     : None. Imports findplus.api.create_app() and calls app.openapi()
             directly — no server, no network.
Outputs    : .github/wiki/API-reference.md, one "## {tag}" section per pinned
             tag (api-contract.md §OpenAPI order), one "### {METHOD} {path}"
             per operation under its tag.
Constraints: Tag order is the spec's pinned order, not alphabetical. "alerts"
             always gets a heading even with zero routes (E6 adds them in W6).
"""

from __future__ import annotations

import pathlib
import sys

sys.path.insert(
    0, str(pathlib.Path(__file__).resolve().parent.parent.parent / "cli" / "src")
)

#: api-contract.md §OpenAPI — pinned order, not alphabetical.
TAG_ORDER = [
    "core",
    "lock",
    "settings",
    "devices",
    "icons",
    "history",
    "places",
    "groups",
    "alerts",
    "providers",
    "auth",
]

OUTPUT = (
    pathlib.Path(__file__).resolve().parent.parent.parent
    / ".github"
    / "wiki"
    / "API-reference.md"
)


def _param_type(schema: dict) -> str:
    if "type" in schema:
        return schema["type"]
    for option in schema.get("anyOf", []):
        if option.get("type") not in (None, "null"):
            return option["type"]
    return "any"


def _param_table(parameters: list[dict]) -> list[str]:
    if not parameters:
        return []
    lines = ["", "| name | in | required | type |", "|---|---|---|---|"]
    for p in parameters:
        lines.append(
            f"| {p['name']} | {p['in']} | {p.get('required', False)} "
            f"| {_param_type(p.get('schema', {}))} |"
        )
    return lines


def _request_body(operation: dict, components: dict) -> list[str]:
    body = operation.get("requestBody")
    if not body:
        return []
    import json

    schema = body["content"]["application/json"]["schema"]
    ref = schema.get("$ref")
    if ref:
        name = ref.rsplit("/", 1)[-1]
        schema = components.get("schemas", {}).get(name, schema)
    return ["", "**Request body:**", "```json", json.dumps(schema, indent=2), "```"]


def _tag_map(paths: dict) -> dict[str, list[tuple[str, str, dict]]]:
    """{tag: [(METHOD, path, operation), ...]}, insertion order per path."""
    by_tag: dict[str, list[tuple[str, str, dict]]] = {}
    for path, methods in paths.items():
        for method, operation in methods.items():
            for tag in operation.get("tags", ["core"]):
                by_tag.setdefault(tag, []).append((method.upper(), path, operation))
    return by_tag


def render(schema: dict) -> tuple[str, int]:
    by_tag = _tag_map(schema["paths"])
    components = schema.get("components", {})
    lines = [
        "# API reference",
        "",
        "Generated by `packaging/scripts/gen-api-docs.py`. Do not hand-edit.",
        "",
    ]
    unknown = sorted(set(by_tag) - set(TAG_ORDER))
    if unknown:
        # A tag missing from TAG_ORDER used to drop its routes silently, so the
        # reference could pass its own drift gate while documenting nothing.
        raise SystemExit(f"tags missing from TAG_ORDER: {unknown}")
    route_count = 0
    for tag in TAG_ORDER:
        lines.append(f"## {tag}")
        for method, path, operation in sorted(by_tag.get(tag, [])):
            route_count += 1
            lines.append(f"### {method} {path}")
            summary = operation.get("description") or operation.get("summary") or ""
            if summary:
                lines.append(summary.splitlines()[0])
            lines.extend(_param_table(operation.get("parameters", [])))
            lines.extend(_request_body(operation, components))
            lines.append("")
    return "\n".join(lines) + "\n", route_count


def main() -> None:
    from findplus.api import create_app

    schema = create_app().openapi()
    text, route_count = render(schema)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"Wrote .github/wiki/API-reference.md ({route_count} routes)")


if __name__ == "__main__":
    main()
