"""Regenerate the generated parts of the dashboard's English catalog.

Purpose    : `cli/src/findplus/honesty.py` is the single source of truth for the
             sentences specs/honesty.md pins. This script copies every entry of
             its `NOTICES` dict into `web/locales/en.json`'s `honesty` namespace
             so the browser catalog can never paraphrase them, and rewrites
             `web/app/catalog-en.js` — the bundled fallback i18n.js uses when the
             catalog fetch fails — from the finished JSON.
Inputs     : None. Imports `findplus.honesty` directly (no subprocess, so the
             package need not be installed) and reads the committed en.json.
Outputs    : web/locales/en.json (its `honesty` block replaced) and
             web/app/catalog-en.js (the whole catalog, as an ES module).
Constraints: Iterates `honesty.NOTICES` — never a hardcoded key list or count —
             so a later ticket adding a sentence needs no change here. Run it
             after any edit to honesty.py OR to en.json; the local drift test
             (cli/tests/test_i18n_catalog.py) and CI's docs-drift job both re-run
             this and diff the result against HEAD.
SPORT      : master-inventories.md § E9-S1: i18n scaffold (P2-E9-W2-S1-T1).
"""

from __future__ import annotations

import json
import pathlib
import sys

sys.path.insert(
    0, str(pathlib.Path(__file__).resolve().parent.parent.parent / "cli" / "src")
)

from findplus import honesty

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
OUTPUT = REPO_ROOT / "web" / "locales" / "en.json"
FALLBACK = REPO_ROOT / "web" / "app" / "catalog-en.js"

FALLBACK_HEADER = """\
/*
 * Find+ dashboard — bundled English catalog.
 *
 * Purpose    : The fallback i18n.js falls through to when /static/locales/en.json
 *              cannot be fetched, or when a loaded catalog is missing a key. It
 *              is what keeps the UI from ever rendering a raw dotted key.
 * Inputs     : None — a data module, no behaviour.
 * Outputs    : CATALOG_EN, the same object web/locales/en.json holds.
 * Constraints: GENERATED BY packaging/scripts/gen-honesty-json.py from
 *              web/locales/en.json. Do not hand-edit: edit en.json (or
 *              honesty.py for the honesty block) and re-run the script.
 */
"use strict";

export const CATALOG_EN = """


def _camel(snake_id: str) -> str:
    """`lock_not_encryption` -> `lockNotEncryption`, the catalog's key style."""
    parts = snake_id.split("_")
    return parts[0] + "".join(part.capitalize() for part in parts[1:])


def _write_fallback(data: dict) -> None:
    """Rewrite catalog-en.js so the bundled fallback cannot drift from en.json."""
    body = json.dumps(data, indent=2, ensure_ascii=False)
    FALLBACK.write_text(f"{FALLBACK_HEADER}{body};\n", encoding="utf-8")


def main() -> None:
    data = json.loads(OUTPUT.read_text(encoding="utf-8"))
    data["honesty"] = {_camel(key): text for key, text in honesty.NOTICES.items()}
    OUTPUT.write_text(
        json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    _write_fallback(data)


if __name__ == "__main__":
    main()
