"""Render the `findplus` Click command tree to .github/wiki/CLI-reference.md.

Purpose    : Keep the committed CLI reference in lock-step with the code —
             the local drift check (definition_of_done) re-runs this and
             diffs the result against HEAD; CI does the same from E14.
Inputs     : None. Imports the root Click group directly (no subprocess, so
             findplus need not be on PATH) and walks its command tree.
Outputs    : .github/wiki/CLI-reference.md, one "## findplus {path}" section
             per leaf command (group commands recurse into their subcommands
             instead of getting a section of their own).
Constraints: Options only (click.Argument entries are skipped — they have no
             default/help worth tabulating the way options do).
"""

from __future__ import annotations

import pathlib
import sys

sys.path.insert(
    0, str(pathlib.Path(__file__).resolve().parent.parent.parent / "cli" / "src")
)

import click

OUTPUT = (
    pathlib.Path(__file__).resolve().parent.parent.parent
    / ".github"
    / "wiki"
    / "CLI-reference.md"
)


def _option_table(params: list) -> list[str]:
    options = [p for p in params if isinstance(p, click.Option)]
    if not options:
        return []
    lines = ["", "| option | default | help |", "|---|---|---|"]
    for opt in options:
        names = ", ".join(opt.opts)
        # Click 8.5's "no default given" sentinel (type name "Sentinel") should
        # render the same as an explicit None — never leak its repr into docs.
        no_default = opt.is_flag or opt.default in (None, False)
        no_default = no_default or type(opt.default).__name__ == "Sentinel"
        default = "" if no_default else str(opt.default)
        help_text = (opt.help or "").replace("|", "\\|")
        lines.append(f"| {names} | {default} | {help_text} |")
    return lines


def _walk(name: str, command, prefix: str, lines: list[str]) -> int:
    """Append one leaf command's section (or recurse into a group's). Returns count."""
    full_name = f"{prefix} {name}".strip()
    if isinstance(command, click.Group):
        count = 0
        for sub_name, sub_command in sorted(command.commands.items()):
            count += _walk(sub_name, sub_command, full_name, lines)
        return count

    lines.append(f"## findplus {full_name}")
    help_line = (command.help or command.short_help or "").strip().splitlines()
    if help_line:
        lines.append(help_line[0])
    lines.append("")
    lines.append(f"**Usage:** `findplus {full_name} [OPTIONS]`")
    lines.extend(_option_table(command.params))
    lines.append("")
    return 1


def render(root: click.Group) -> tuple[str, int]:
    lines = [
        "# CLI reference",
        "",
        "Generated by `packaging/scripts/gen-cli-docs.py`. Do not hand-edit.",
        "",
    ]
    count = 0
    for name, command in sorted(root.commands.items()):
        count += _walk(name, command, "", lines)
    return "\n".join(lines) + "\n", count


def main() -> None:
    from findplus.cli.main import main as cli_main

    text, count = render(cli_main)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"Wrote .github/wiki/CLI-reference.md ({count} commands)")


if __name__ == "__main__":
    main()
