#!/usr/bin/env bash
# lint-prose.sh — ban marketing words, AI tells and em-dashes from docs.
#
# Purpose    : Enforce GCI human-tone rules on README and wiki content.
# Inputs     : one or more file paths, as arguments.
# Outputs    : "lint-prose: <file> OK" per clean file; exit 1 on any hit.
# Constraints: pure grep, no external dependencies.
set -euo pipefail

FILES=("$@")
PATTERN='(Find My\+|seamlessly|robust|comprehensive|powerful|leverage|moreover|furthermore|dive into|delve into|Co-Authored-By|Generated by Claude)'
FOUND=0

for f in "${FILES[@]}"; do
  FILE_BAD=0
  if grep -nE "$PATTERN" "$f"; then
    echo "lint-prose: $f FAIL (banned word/phrase)"
    FILE_BAD=1
  fi
  if grep -n $'\xe2\x80\x94' "$f"; then
    echo "lint-prose: $f FAIL (em-dash)"
    FILE_BAD=1
  fi
  if [ "$FILE_BAD" -eq 0 ]; then
    echo "lint-prose: $f OK"
  else
    FOUND=1
  fi
done

exit "$FOUND"
