#!/usr/bin/env bash
# lint-prose.sh — ban marketing words, AI tells and em-dashes from docs;
# for README.md, also assert every honesty.py sentence appears verbatim.
#
# Purpose    : Enforce GCI human-tone rules on README and wiki content, and
#              keep the six honesty notices (cli/src/findplus/honesty.py)
#              from silently drifting out of README.md.
# Inputs     : one or more file paths, as arguments.
# Outputs    : "lint-prose: <file> OK" per clean file; exit 1 on any hit.
# Constraints: pure grep, no external dependencies. The honesty check is a
#              distinctive-substring match, not a byte-for-byte diff, so it
#              tolerates markdown line-wrapping.
set -euo pipefail

FILES=("$@")
PATTERN='(Find My\+|seamlessly|robust|comprehensive|powerful|leverage|moreover|furthermore|dive into|delve into|Co-Authored-By|Generated by Claude)'
HONESTY_SUBSTRINGS=(
  "Moto Tag uses nearby participating Android devices"
  "genuine AirTags require extracting pairing keys"
  "Alerts inherit the network's delay"
  "stale, not at home and not left behind"
  "The app lock stops casual browsing"
  "not affiliated with Apple or Google"
)
FOUND=0

for f in "${FILES[@]}"; do
  FILE_BAD=0
  if grep -nE "$PATTERN" "$f"; then
    echo "lint-prose: $f FAIL (banned word/phrase)"
    FILE_BAD=1
  fi
  if grep -n $'\xe2\x80\x94' "$f"; then
    echo "lint-prose: $f FAIL (em-dash)"
    FILE_BAD=1
  fi
  if [ "$(basename "$f")" = "README.md" ]; then
    for s in "${HONESTY_SUBSTRINGS[@]}"; do
      if ! grep -qF "$s" "$f"; then
        echo "lint-prose: $f FAIL (missing honesty sentence: $s)"
        FILE_BAD=1
      fi
    done
  fi
  if [ "$FILE_BAD" -eq 0 ]; then
    echo "lint-prose: $f OK"
  else
    FOUND=1
  fi
done

exit "$FOUND"
