#!/usr/bin/env bash
# lint-prose.sh — ban marketing words, AI tells and em-dashes from docs;
# for README.md, also assert every honesty.py sentence appears verbatim.
#
# Purpose    : Enforce GCI human-tone rules on README and wiki content, and
#              keep the six honesty notices (cli/src/findplus/honesty.py)
#              from silently drifting out of README.md.
# Inputs     : one or more file paths, as arguments.
# Outputs    : "lint-prose: <file> OK" per clean file; exit 1 on any hit.
# Constraints: pure grep, no external dependencies. The honesty check is a
#              distinctive-substring match, not a byte-for-byte diff, so it
#              tolerates markdown line-wrapping. EM_DASH_ALLOWED is the one
#              exception to the em-dash ban: two honesty.py sentences are
#              pinned WITH an em dash, so a page quoting either of them
#              verbatim would otherwise be unlintable. The fragments below
#              carry enough context that only a verbatim quote matches, which
#              means the quoted line must keep those words together.
set -euo pipefail

FILES=("$@")
PATTERN='(Find My\+|seamlessly|robust|comprehensive|powerful|leverage|moreover|furthermore|dive into|delve into|Co-Authored-By|Generated by Claude)'
HONESTY_SUBSTRINGS=(
  "trackers use nearby participating Android devices"
  "genuine AirTags require extracting pairing keys"
  "Alerts inherit the network's delay"
  "stale, not at home and not left behind"
  "The app lock stops casual browsing"
  "not affiliated with Apple or Google"
)
# Verbatim fragments of honesty.NOTICES entries that are pinned with an em dash
# (native_generic). Never widen this list to silence a new em dash: add the
# sentence to honesty.py first, then its fragment here.
EM_DASH_ALLOWED=(
  "place — anyone who can see"
)
FOUND=0

for f in "${FILES[@]}"; do
  FILE_BAD=0
  if grep -nE "$PATTERN" "$f"; then
    echo "lint-prose: $f FAIL (banned word/phrase)"
    FILE_BAD=1
  fi
  DASH_HITS="$(grep -n $'\xe2\x80\x94' "$f" || true)"
  for allowed in "${EM_DASH_ALLOWED[@]}"; do
    if [ -n "$DASH_HITS" ]; then
      DASH_HITS="$(printf '%s\n' "$DASH_HITS" | grep -vF -- "$allowed" || true)"
    fi
  done
  if [ -n "$DASH_HITS" ]; then
    printf '%s\n' "$DASH_HITS"
    echo "lint-prose: $f FAIL (em-dash)"
    FILE_BAD=1
  fi
  if [ "$(basename "$f")" = "README.md" ]; then
    for s in "${HONESTY_SUBSTRINGS[@]}"; do
      if ! grep -qF "$s" "$f"; then
        echo "lint-prose: $f FAIL (missing honesty sentence: $s)"
        FILE_BAD=1
      fi
    done
  fi
  if [ "$FILE_BAD" -eq 0 ]; then
    echo "lint-prose: $f OK"
  else
    FOUND=1
  fi
done

exit "$FOUND"
