/*
 * Find+ dashboard — bundled English catalog.
 *
 * Purpose    : The fallback i18n.js falls through to when /static/locales/en.json
 *              cannot be fetched, or when a loaded catalog is missing a key. It
 *              is what keeps the UI from ever rendering a raw dotted key.
 * Inputs     : None — a data module, no behaviour.
 * Outputs    : CATALOG_EN, the same object web/locales/en.json holds.
 * Constraints: GENERATED BY packaging/scripts/gen-honesty-json.py from
 *              web/locales/en.json. Do not hand-edit: edit en.json (or
 *              honesty.py for the honesty block) and re-run the script.
 */
"use strict";

export const CATALOG_EN = {
  "common": {
    "appName": "Find+",
    "save": "Save",
    "cancel": "Cancel",
    "close": "Close",
    "delete": "Delete",
    "clear": "Clear",
    "remove": "Remove",
    "refresh": "Refresh",
    "loading": "Loading…",
    "error": "Error",
    "emptyValue": "—",
    "lockTitle": "Find+ is locked",
    "lockSub": "Enter your PIN to continue.",
    "unlock": "Unlock",
    "pin": "PIN",
    "liveDotTitle": "Polling service status",
    "deviceNamePlaceholder": "no tracker selected",
    "btnDevices": "Devices",
    "btnSettings": "Settings",
    "btnLock": "Lock",
    "btnLockTitle": "Lock now",
    "btnLatest": "Latest Location",
    "btnPoll": "Poll Now",
    "btnPollTitle": "Queries your providers once, now",
    "cardObservedLabel": "Last observed",
    "cardFetchedLabel": "Retrieved by this computer",
    "cardPollLabel": "Last successful poll",
    "cardTodayLabel": "Observations today",
    "show": "Show",
    "groupLabel": "Group:",
    "day": "Day",
    "prevDay": "Previous day",
    "nextDay": "Next day",
    "today": "Today",
    "movementOnly": "Movement only",
    "export": "Export",
    "exportScope": "Scope",
    "exportFormatCsv": "CSV",
    "exportFormatGpx": "GPX",
    "exportFormatJson": "JSON",
    "exportFormatKml": "KML",
    "exportScopeDay": "This day",
    "exportScopeRange": "Date range…",
    "exportScopeAll": "All history",
    "rangeStart": "Range start",
    "rangeEnd": "Range end",
    "rangeSeparator": "to",
    "download": "Download",
    "tabDashboard": "Dashboard",
    "tabPlaces": "Places",
    "tabGroups": "Groups",
    "tabAlerts": "Alerts",
    "more": "More",
    "footerPrivacy": "Runs entirely on this computer and binds to 127.0.0.1. No analytics, telemetry or third-party scripts. Map tiles are fetched from OpenStreetMap, which necessarily sees the tile coordinates being viewed."
  },
  "devices": {
    "title": "Your devices",
    "note": "Tick every tracker you want polled. Each tracked device costs one provider request per poll cycle, so the request rate rises with the number you tick. Untracking keeps a device's existing history — it just stops being polled.",
    "allTracked": "All tracked devices",
    "refreshProvidersLabel": "Refresh from your providers",
    "trackNone": "Track none",
    "trackAll": "Track all"
  },
  "groups": {
    "tabHint": "Use the Group selector above the map to choose a group.",
    "allDevices": "— All devices —"
  },
  "places": {
    "addPlace": "Add place",
    "tabHint": "Click the map or use Add place to create a geofence."
  },
  "alerts": {
    "telegramHeading": "Telegram",
    "webhookHeading": "Webhook",
    "botToken": "Bot token",
    "connect": "Connect",
    "sendTest": "Send test",
    "url": "URL",
    "urlPlaceholder": "https://example.com/hook",
    "secret": "Secret",
    "secretPlaceholder": "Optional secret",
    "rulesHeading": "Rules",
    "addRule": "Add rule",
    "colName": "Name",
    "colPlace": "Place",
    "colTarget": "Device or Group",
    "colOnEnter": "On enter",
    "colOnExit": "On exit",
    "colChannel": "Channel",
    "colActions": "Actions",
    "deliveryLogHeading": "Delivery log",
    "colRule": "Rule",
    "colKind": "Kind",
    "colSent": "Sent",
    "colStatus": "Status",
    "colError": "Error",
    "showMapInWidget": "Show map in widget",
    "widgetMapDisclaimer": "The map preview sends the coordinate region to Apple Maps.",
    "targetDevice": "Device",
    "targetGroup": "Group",
    "cooldownMinutes": "Cooldown (minutes)"
  },
  "settings": {
    "title": "Settings",
    "appearanceHeading": "Appearance",
    "theme": "Theme",
    "themeDark": "Dark",
    "themeLight": "Light",
    "themeSystem": "Match system",
    "desktopHeading": "Desktop app",
    "startAtLogin": "Start Find+ at login",
    "appLockHeading": "App lock",
    "newPin": "New PIN",
    "newPinPlaceholder": "at least 6 characters",
    "confirmPin": "Confirm PIN",
    "setPin": "Set PIN",
    "lockEnabled": "Lock enabled",
    "autoLockIdle": "Auto-lock after idle",
    "idleNever": "Never",
    "idle1Minute": "1 minute",
    "idle5Minutes": "5 minutes",
    "idle15Minutes": "15 minutes",
    "idle30Minutes": "30 minutes",
    "idle1Hour": "1 hour",
    "currentPin": "Current PIN",
    "currentPinPlaceholder": "required to change or remove",
    "newPinOptional": "New PIN (optional)",
    "changePin": "Change PIN",
    "removePin": "Remove PIN",
    "deleteHistoryHeading": "Delete history",
    "deleteHistoryNote": "History is never deleted silently. Both actions show you exactly how many observations would go, and ask again before anything is removed.",
    "deleteBefore": "Delete observations before",
    "deleteOlder": "Delete older than…",
    "clearAll": "Clear ALL history",
    "aboutHeading": "About",
    "noticesHeading": "Notices"
  },
  "setup": {
    "stepWelcome": "Welcome"
  },
  "auth": {
    "signInGoogle": "Sign in with Google"
  },
  "notices": {
    "pathDisclaimer": "Observed path — actual route between detections may differ."
  },
  "honesty": {
    "findHub": "This history consists of locations reported through Google's Find Hub network. Moto Tag uses nearby participating Android devices to report its location. Location updates can therefore be delayed, sparse, or unavailable, and this application should not be treated as real-time emergency or child-safety GPS tracking.",
    "apple": "Apple Find My locations come from nearby Apple devices and can be delayed, sparse or unavailable. Find+ can only query accessories whose keys you hold; genuine AirTags require extracting pairing keys, which most users cannot do.",
    "alertsLatency": "Alerts inherit the network's delay. An arrival or departure may be reported minutes to hours late.",
    "presenceStale": "A tag with no recent fix is stale, not at home and not left behind. Find+ reports it as unknown.",
    "lockNotEncryption": "The app lock stops casual browsing. It does not encrypt the database; anyone with access to this user account or the disk can read it. Use FileVault.",
    "notAffiliated": "Find+ is not affiliated with Apple or Google. Find Hub and Find My are their trademarks."
  }
};
